routes/web.php
<?php

use App\Http\Controllers\Client\HomeController;
use App\Mail\AdminWhenClientApplyFormMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);
Auth::routes();


Route::controller(\App\Http\Controllers\Client\HomeController::class)->group(function () {
    Route::get('/', 'index')->name('client.home');
    Route::get('/customize-tour', 'getCustomizeTour')->name('client.customize_tour');

});

Route::controller(\App\Http\Controllers\Client\SlugController::class)
    ->group(function () {
        Route::get('/{slug}', 'slug')->name('client.slug');
    });


Route::controller(\App\Http\Controllers\Client\TourController::class)
    ->name('client.tours.')->group(function () {
        Route::get('/bookingtour-{slug}', 'bookTourForm')->name('book_tour_form');
        Route::post('/book-tour/store', 'bookTour')->name('book_tour');
    });

Route::controller(\App\Http\Controllers\Client\CustomerContactController::class)
    ->name('client.customer_contacts.')->group(function () {
        Route::post('customer-contacts-create', 'store')->name('store');

    });

//
Route::post('contactuses-store', [App\Http\Controllers\ContactUsController::class,'store'])->name('contactuses-store');

Route::get('/checkOnline', function (App\Repositories\AttendanceRepository $attendanceRepo) {
    if (Auth::check()) {
    }
    return $attendanceRepo->CountUserOnline();
})->name('checkOnline');

app/Models/Post.php
<?php

namespace App\Models;

use App\Traits\SlugAbleCustom;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class Post
 * @package App\Models
 * @version February 4, 2023, 2:23 pm +07
 *
 * @property string $name
 * @property string $slug
 * @property string $desc
 * @property string $content
 * @property string $image
 */
class Post extends Model
{
    use SoftDeletes;

    use SlugDefault;

    use HasFactory;

    use SlugAbleCustom;

    const IMAGE_PATH = 'posts/';

    const ACTIVE_STATUS = 1;

    public $table = 'posts';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'slug',
        'desc',
        'content',
        'image',
        'is_inspiration',
        'is_travel_article',
        'thumbnail',
        'header_image',
        'is_show_in_home',
        'is_in_first_home',
        'meta'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'slug' => 'string',
        'desc' => 'string',
        'image' => 'string',
        'meta' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => ['required', 'max:255'],
        'desc' => 'required|string',
        'image' => ['nullable', 'mimetypes:image/png,image/jpeg,image/jpg', 'max:4024'],
        'thumbnail' => ['nullable', 'mimetypes:image/png,image/jpeg,image/jpg', 'max:4024'],
        'header_image' => ['nullable', 'mimetypes:image/png,image/jpeg,image/jpg', 'max:4024'],
        'content' => ['nullable'],
        'meta' => ['nullable'],
    ];

    public function categories()
    {
        return $this->belongsToMany(PostCategory::class, 'post_category', 'post_id', 'post_category_id');
    }

    public function syncCategory($id)
    {
        return $this->categories()->sync($id);
    }

    public function scopeSearchByName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }


    public function scopeSearchByCategory($query, $postCategoryId)
    {
        if ($postCategoryId > 0 && $postCategoryId !== null) {
            return $query->whereHas('categories', function ($query) use ($postCategoryId) {
                $query->where('id', $postCategoryId);
            });
        }
    }

    public function getImagePathAttribute()
    {
        return asset(self::IMAGE_PATH . $this?->image);
    }

    public function getThumbnailPathAttribute()
    {
        return $this?->thumbnail ? asset(self::IMAGE_PATH . $this?->thumbnail)
            : asset('clients/assets/images/inspiration/Layer 34.png');
    }

    public function getHeaderImagePathAttribute()
    {
        return $this->header_image ? asset(self::IMAGE_PATH . $this?->header_image)
            : asset('clients/assets/images/header_bg.png');
    }

    public function scopeWithIsInspiration($query)
    {
        return $query->where('is_inspiration', self::ACTIVE_STATUS);
    }

    public function scopeWithIsTravelArticle($query)
    {
        return $query->where('is_travel_article', self::ACTIVE_STATUS);
    }

    public function scopeWithShowInHome($query)
    {
        return $query->where('is_show_in_home', self::ACTIVE_STATUS);
    }

    public function scopeWithFirstInHome($query)
    {
        return $query->where('is_in_first_home', self::ACTIVE_STATUS);
    }

    public function scopeWithPostCategoryId($query, $postCategoryId)
    {
        return $query->whereHas('categories', fn($q) =>$q-> where('post_categories.id', $postCategoryId));
    }

    public function getSlugCategoryLinkAttribute()
    {
        return count($this->categories) > 0 ? route('client.slug', $this->categories->first()->slug_custom_name)
            : route('client.home');
    }
}

app/Http/Controllers/Client/BlogController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.blogs.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('client.blogs.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/CategoryController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\TourCategoryService;
use App\Services\TourService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    protected TourCategoryService $tourCategoryService;
    protected TourService $tourService;

    /**
     * @param TourCategoryService $tourCategoryService
     * @param TourService $tourService
     */
    public function __construct(TourCategoryService $tourCategoryService, TourService $tourService)
    {
        $this->tourCategoryService = $tourCategoryService;
        $this->tourService = $tourService;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($slug)
    {

        $tourCategory = $this->tourCategoryService->findBySlug($slug);
        $tours = $this->tourService->getTourOfCategory($tourCategory->id);
        return view('client.categories.index',compact('tourCategory','tours'));
    }
}

app/Http/Controllers/Client/CustomerContactController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCustomerContactRequest;
use App\Jobs\SentEmailToAdminWhenClientApplyFormJob;
use App\Jobs\SentEmailToClientWhenApplyFormJob;
use App\Repositories\CustomerContactRepository;
use Illuminate\Http\Request;
use Flash;


class CustomerContactController extends Controller
{
    protected CustomerContactRepository $customerContactRepository;

    /**
     * @param CustomerContactRepository $customerContactRepository
     */
    public function __construct(CustomerContactRepository $customerContactRepository)
    {
        $this->customerContactRepository = $customerContactRepository;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCustomerContactRequest $request)
    {
        $input = $request->all();

        $customerContact = $this->customerContactRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/customerContacts.singular')]));
        $this->dispatch(new SentEmailToAdminWhenClientApplyFormJob($customerContact));
        $this->dispatch(new SentEmailToClientWhenApplyFormJob($customerContact));

        return redirect(route('client.home'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Jobs\SentEmailToAdminWhenClientApplyFormJob;
use App\Repositories\SettingRepository;
use App\Repositories\TourRepository;
use App\Services\HomeSlideService;
use App\Services\PostService;
use App\Services\SettingService;
use App\Services\TourCategoryService;
use App\Services\TourService;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    protected TourService $tourService;
    protected PostService $postService;
    protected TourCategoryService $tourCategoryService;
    protected SettingService $settingService;
    protected HomeSlideService $homeSlideService;

    /**
     * @param TourService $tourService
     * @param PostService $postService
     * @param TourCategoryService $tourCategoryService
     * @param SettingService $settingService
     */
    public function __construct(
        TourService $tourService,
        PostService $postService,
        TourCategoryService $tourCategoryService,
        SettingService $settingService,
        HomeSlideService $homeSlideService
    ) {
        $this->tourService = $tourService;
        $this->postService = $postService;
        $this->tourCategoryService = $tourCategoryService;
        $this->settingService = $settingService;
        $this->homeSlideService = $homeSlideService;
    }


    public function index()
    {
        $tours = $this->tourService->getTourShowInHomeClient();
        $postFirstInHome = $this->postService->getShowFirstInHomeClient();

        $quantity = $postFirstInHome ? 2 : 3;
        $postsShow = $this->postService->getShowInHomeClient(3);
        if($postFirstInHome)
        {
            $posts = $postsShow->where('id','!=',$postFirstInHome->id);
        }
        $touCategoryFirst = $this->tourCategoryService->first();
        $tourCategoryWithTour = $this->tourCategoryService->getTourCategoryByStyleWithTour();
        $multiTourContent = $this->settingService->getMultiTourInHome();
        $homeSlides = $this->homeSlideService->allPublic();
        return view('client.home.index',compact('tours','posts','tourCategoryWithTour', 'multiTourContent','touCategoryFirst','postFirstInHome','homeSlides'));
    }


    public function getCustomizeTour()
    {
        $touCategoryFirst = $this->tourCategoryService->first();
        return view('client.customize-tour.index', compact('touCategoryFirst'));
    }
}

app/Http/Controllers/Client/PostCategoryController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\PostCategoryService;
use App\Services\PostService;
use Illuminate\Http\Request;

class PostCategoryController extends Controller
{
    protected PostCategoryService $postCategoryService;
    protected PostService $postService;

    /**
     * @param PostCategoryService $postCategoryService
     * @param PostService $postService
     */
    public function __construct(PostCategoryService $postCategoryService, PostService $postService)
    {
        $this->postCategoryService = $postCategoryService;
        $this->postService = $postService;
    }


    public function show($slug)
    {
        $postsInspiration = $this->postService->getWithPaginate(6);
        $morePosts = $this->postService->getWithPaginate(3);
        return view('client.blogs.index', compact('postsInspiration', 'morePosts'));
    }



}

app/Http/Controllers/Client/PostController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\PostService;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected PostService $postService;

    /**
     * @param PostService $postService
     */
    public function __construct(PostService $postService)
    {
        $this->postService = $postService;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $post = $this->postService->findBySlug($slug);
        $postsInspiration = $this->postService->getPostInspirationInDetailPost();
        return view('client.blogs.show',compact('post', 'postsInspiration'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/client/blogs/index.blade.php
@section('style')
    <link rel="stylesheet" href="{{asset('clients/assets/css/blog.css')}}"/>
@endsection
@extends('client.layouts.app')
@section('header_image')
    <div class="header-image">
        <picture>
            <source
                media="(max-width: 767px)"
                data-srcset="{{asset('clients/assets/images/header_bg_sm.png')}}"
                data-sizes="auto"
                class="lazyload"
            />
            <source
                media="(min-width: 768px)"
                data-srcset="{{asset('clients/assets/images/header_bg.png')}}"
                data-sizes="auto"
                class="lazyload"
            />
            <img
                src="{{asset('clients/assets/images/header_bg.png')}}"
                alt="Image description"
                class="img-response lazyload"
            />
        </picture>
{{--        <img data-src="{{asset('clients/assets/images/header_bg.png')}}" class="img-response lazyload" alt=""/>--}}
    </div>
@endsection
@section('title')
    {!! $postCategory->title ??  $postCategory->name !!}
@endsection
@section('meta')
    {!! $postCategory->meta !!}
@endsection
@section('header_banner')
    <div class="header-banner header-banner-tour">

    </div>
@endsection
@section('main')
    <section class="blog-service container">
        <div class="blog-service-head">
            <div class="blog-service-head__title">
                <h1>Travel Inspiration</h1>
                <img
                    class="blog-service-head__line"
                    src="{{asset('clients/assets/images/tours/tour-title-line.png')}}"
                    alt=""
                />
            </div>

            <div class="blog-service-head__des">
                <p>
                    The opening of Vietnam means you are free to explore more the
                    hiden gems of the country. From exotic markets to vibrant cities,
                    Vietnam is very tempting. Keep your best memory of Vietnam with
                    our carefully designed tours
                </p>

            </div>
        </div>
        @if(!(request()->page && request()->page > 1))
        <div class="posts ">
            <div class="blog-items row">

                @foreach($postsInspiration as $item)
                    <div class="col-12 col-sm-4 col-md-4">
                        <div class="blog-item">
                            <a class="blog-item__img" href="{{route('client.slug',$item->slug_custom_name)}}">
                                <img
                                    src="{{$item->image_path}}"
                                    alt="{{$item->name}}"
                                />
                            </a>
                            <a class="blog-item__name d-block text-center text-dark" href="{{route('client.slug',$item->slug_custom_name)}}">{{$item->name}}</a>
                            <div class="blog-item-des">
                                <div class="blog-item-des__content text-over2">
                                    {{$item->desc}}
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
        @endif
    </section>

    @if(!(request()->page && request()->page > 1))
    <section class="article-service">
        <div class="article-service-image">
            <img data-src="{{asset('clients/assets/images/feature-article/background.png')}}" class="lazyload" />
        </div>
        <div class="article-service-content">
            <div class="article-service-head">
                <p class="article-service-head__title">
                    <span>Featured Article </span>
                    <img
                        class="article-service-head__line"
                        src="{{asset('clients/assets/images/tours/tour-title-line.png')}}"
                        alt=""
                    />
                </p>
            </div>
            <div class="article-service-des pt-2 pt-sm-2 pt-md-2">
                <p class="article-service-des__title">How to spend 3 days with halong bay</p>
                <p class="article-service-des__des">For those who are seeking for an idea to explore Halong </p>
            </div>
        </div>
    </section>

    <section class="suggetion-service">
        <div class="suggetion-service-head">
            <p class="suggetion-service-head__title">
                <span>Insider Travel Suggestion </span>
                <img
                    class="suggetion-service-head__line"
                    src="{{asset('clients/assets/images/tours/tour-title-line.png')}}"
                    alt=""
                />
            </p>
        </div>
        <div class="suggetion-service-des">
            <p>Autumn is a wonderful time to admire the rice
                terraces in northern Vietnam. From Mu Cang
                Chai to Sapa, Ha Giang, picture-poscard sites
                are abundant !
            </p>
        </div>
    </section>

    @endif

    <section class="moreblog-service container">
        @if(!(request()->page && request()->page > 1))
        <div class="moreblog-service-head">
            <p class="moreblog-service-head__title">
                <span>More Travel Articles</span>
                <img
                    class="moreblog-service-head__line"
                    src="{{asset('clients/assets/images/tours/tour-title-line.png')}}"
                    alt=""
                />
            </p>

            <div class="moreblog-service-head__des">
            </div>
        </div>
        @endif
        <div class="posts ">
            <div class="blog-items row">

                @foreach($morePosts->get('posts') as $item)
                    <div class="col-12 col-sm-4 col-md-4">
                        <div class="blog-item">
                            <a class="blog-item__img" href="{{route('client.slug',$item->slug_custom_name)}}">
                                <img
                                    src="{{$item->image_path}}"
                                    alt=""
                                />
                            </a>
                            <a class="blog-item__name d-block text-center text-dark" href="{{route('client.slug',$item->slug_custom_name)}}">{{$item->name}}</a>
                            <div class="blog-item-des">
                                <div class="blog-item-des__content text-over2">
                                    {{$item->desc}}
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="d-flex justify-content-end more-post-paginate" style="margin-top: 102px">
            <ul class="pagination m-0">
                @if($morePosts->get('meta')['first'])
                <li class="page-item">
                    <a class="page-link" href="{{$morePosts->get('meta')['first']}}" rel="prev" aria-label="« Trang sau">«</a>
                </li>
                @endif
                @if(count($morePosts->get('links')) > 1)
                    @foreach($morePosts->get('links') as $key => $val)
                            @if($morePosts->get('currentPage') ==  ($key+1) )
                                <li class="page-item active" aria-current="page"><span class="page-link">{{$key+1}}</span></li>

                            @else
                                <li class="page-item"><a class="page-link" href="{{$val}}">{{$key+1}}</a></li>

                            @endif
                        @endforeach
                 @endif
                    @if($morePosts->get('meta')['first'])
                        <li class="page-item">
                            <a class="page-link" href="{{$morePosts->get('meta')['first']}}" rel="next" aria-label="Trang trước »">»</a>
                        </li>
                    @endif
            </ul>
        </div>
    </section>
    <section class="line-service"></section>
@endsection
@section('script')
    <script>
        $(()=>{
            let imageWidth = document.querySelector('.blog-item__img').clientWidth;
            let heightImage = +imageWidth * 1.4;
            if(window.innerWidth > 567)
            {
                $('.tour-item__img').css('height', `${heightImage}px`)
            }

            const resizeObserver = new ResizeObserver(entries => {
                for (let entry of entries) {
                    let imageWidth = document.querySelector('.blog-item__img').clientWidth;
                    let heightImage = +imageWidth * 1.4;
                    if(window.innerWidth > 567)
                    {
                        $('.tour-item__img').css('height', `${heightImage}px`)
                    }
                }
            });
            resizeObserver.observe(document.body); // Add this line if the image is initially hidden
        })
    </script>
@endsection

resources/views/client/blogs/show.blade.php
@section('style')
    <link rel="stylesheet" href="{{asset('clients/assets/css/blog-detail.css')}}" />
@endsection
@extends('client.layouts.app')
@section('meta')
    {!! $post?->meta !!}
@endsection
@section('title')
    {!! $post->name !!}
@endsection

@section('header_image')
    <div class="header-image">
        <img data-src="{{$post->header_image_path}}" class="img-response lazyload" alt="" />
    </div>
@endsection
@section('header_banner')
    <div class="header-banner header-banner-tour"></div>
@endsection
@section('main')
    <section class="content">
        <div class="content-head">
            <div class="content-head__title">
                <h1>{{$post->name}}</h1>
                <img
                    class="blog-service-head__line"
                    src="{{asset('clients/assets/images/tours/tour-title-line.png')}}"
                    alt=""
                />
            </div>
        </div>
        <div class="content-body">
            {!! $post->content !!}
        </div>
    </section>
    <section class="moreblog-service">
        <div class="container">
            <div class="moreblog-service-head">
                <p class="moreblog-service-head__title">
                    <span>More travel inspiration</span>
                    <img
                        class="moreblog-service-head__line"
                        src="{{asset('clients/assets/images/tours/tour-title-line.png')}}"
                        alt=""
                    />
                </p>

                <div class="moreblog-service-head__des"></div>
            </div>
            <div class="posts">
                <div class="blog-items row">
                    @foreach($postsInspiration as $item)
                    <div class="col-12 col-sm-4 col-md-4">
                        <div class="blog-item">
                            <a class="blog-item__img">
                                <img data-src="{{$item->image_path}}" class="lazyload" alt="{{$item->name}}" />
                            </a>
                            <a class="blog-item__name text-center d-block text-dark" href="{{route('client.slug',$item->slug_custom_name)}}">{{$item->name}}</a>
                            <div class="blog-item-des">
                                <div class="blog-item-des__content text-over2">
                                    {{$item->desc}}
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>

            <div class="d-flex justify-content-center pb-5" style="margin-top: 100px">
                <a class="btn btn-more-blog" href="{{route('client.slug', $categorySlug ?? $item->slug_custom_name)}}">View all articles</a>
            </div>
        </div>

    </section>
    <section class="line-service mt-5"></section>
@endsection
@section('script')
    <script>
        document.querySelectorAll('figure.table').forEach(a => {
            a.style.margin = "0 auto"
        })
    </script>
@endsection