routes/web.php
<?php

use App\Http\Controllers\Client\HomeController;
use App\Mail\AdminWhenClientApplyFormMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);
Auth::routes();


Route::controller(\App\Http\Controllers\Client\HomeController::class)->group(function () {
    Route::get('/', 'index')->name('client.home');
    Route::get('/customize-tour', 'getCustomizeTour')->name('client.customize_tour');

});

Route::controller(\App\Http\Controllers\Client\SlugController::class)
    ->group(function () {
        Route::get('/{slug}', 'slug')->name('client.slug');
    });


Route::controller(\App\Http\Controllers\Client\TourController::class)
    ->name('client.tours.')->group(function () {
        Route::get('/bookingtour-{slug}', 'bookTourForm')->name('book_tour_form');
        Route::post('/book-tour/store', 'bookTour')->name('book_tour');
    });

Route::controller(\App\Http\Controllers\Client\CustomerContactController::class)
    ->name('client.customer_contacts.')->group(function () {
        Route::post('customer-contacts-create', 'store')->name('store');

    });

//
Route::post('contactuses-store', [App\Http\Controllers\ContactUsController::class,'store'])->name('contactuses-store');

Route::get('/checkOnline', function (App\Repositories\AttendanceRepository $attendanceRepo) {
    if (Auth::check()) {
    }
    return $attendanceRepo->CountUserOnline();
})->name('checkOnline');

app/Http/Controllers/Client/BlogController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.blogs.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('client.blogs.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/CategoryController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\TourCategoryService;
use App\Services\TourService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    protected TourCategoryService $tourCategoryService;
    protected TourService $tourService;

    /**
     * @param TourCategoryService $tourCategoryService
     * @param TourService $tourService
     */
    public function __construct(TourCategoryService $tourCategoryService, TourService $tourService)
    {
        $this->tourCategoryService = $tourCategoryService;
        $this->tourService = $tourService;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($slug)
    {

        $tourCategory = $this->tourCategoryService->findBySlug($slug);
        $tours = $this->tourService->getTourOfCategory($tourCategory->id);
        return view('client.categories.index',compact('tourCategory','tours'));
    }
}

app/Http/Controllers/Client/CustomerContactController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCustomerContactRequest;
use App\Jobs\SentEmailToAdminWhenClientApplyFormJob;
use App\Jobs\SentEmailToClientWhenApplyFormJob;
use App\Repositories\CustomerContactRepository;
use Illuminate\Http\Request;
use Flash;


class CustomerContactController extends Controller
{
    protected CustomerContactRepository $customerContactRepository;

    /**
     * @param CustomerContactRepository $customerContactRepository
     */
    public function __construct(CustomerContactRepository $customerContactRepository)
    {
        $this->customerContactRepository = $customerContactRepository;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCustomerContactRequest $request)
    {
        $input = $request->all();

        $customerContact = $this->customerContactRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/customerContacts.singular')]));
        $this->dispatch(new SentEmailToAdminWhenClientApplyFormJob($customerContact));
        $this->dispatch(new SentEmailToClientWhenApplyFormJob($customerContact));

        return redirect(route('client.home'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Jobs\SentEmailToAdminWhenClientApplyFormJob;
use App\Repositories\SettingRepository;
use App\Repositories\TourRepository;
use App\Services\HomeSlideService;
use App\Services\PostService;
use App\Services\SettingService;
use App\Services\TourCategoryService;
use App\Services\TourService;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    protected TourService $tourService;
    protected PostService $postService;
    protected TourCategoryService $tourCategoryService;
    protected SettingService $settingService;
    protected HomeSlideService $homeSlideService;

    /**
     * @param TourService $tourService
     * @param PostService $postService
     * @param TourCategoryService $tourCategoryService
     * @param SettingService $settingService
     */
    public function __construct(
        TourService $tourService,
        PostService $postService,
        TourCategoryService $tourCategoryService,
        SettingService $settingService,
        HomeSlideService $homeSlideService
    ) {
        $this->tourService = $tourService;
        $this->postService = $postService;
        $this->tourCategoryService = $tourCategoryService;
        $this->settingService = $settingService;
        $this->homeSlideService = $homeSlideService;
    }


    public function index()
    {
        $tours = $this->tourService->getTourShowInHomeClient();
        $postFirstInHome = $this->postService->getShowFirstInHomeClient();

        $quantity = $postFirstInHome ? 2 : 3;
        $postsShow = $this->postService->getShowInHomeClient(3);
        if($postFirstInHome)
        {
            $posts = $postsShow->where('id','!=',$postFirstInHome->id);
        }
        $touCategoryFirst = $this->tourCategoryService->first();
        $tourCategoryWithTour = $this->tourCategoryService->getTourCategoryByStyleWithTour();
        $multiTourContent = $this->settingService->getMultiTourInHome();
        $homeSlides = $this->homeSlideService->allPublic();
        return view('client.home.index',compact('tours','posts','tourCategoryWithTour', 'multiTourContent','touCategoryFirst','postFirstInHome','homeSlides'));
    }


    public function getCustomizeTour()
    {
        $touCategoryFirst = $this->tourCategoryService->first();
        return view('client.customize-tour.index', compact('touCategoryFirst'));
    }
}

app/Http/Controllers/Client/PostCategoryController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\PostCategoryService;
use App\Services\PostService;
use Illuminate\Http\Request;

class PostCategoryController extends Controller
{
    protected PostCategoryService $postCategoryService;
    protected PostService $postService;

    /**
     * @param PostCategoryService $postCategoryService
     * @param PostService $postService
     */
    public function __construct(PostCategoryService $postCategoryService, PostService $postService)
    {
        $this->postCategoryService = $postCategoryService;
        $this->postService = $postService;
    }


    public function show($slug)
    {
        $postsInspiration = $this->postService->getWithPaginate(6);
        $morePosts = $this->postService->getWithPaginate(3);
        return view('client.blogs.index', compact('postsInspiration', 'morePosts'));
    }



}

app/Http/Controllers/Client/PostController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\PostService;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected PostService $postService;

    /**
     * @param PostService $postService
     */
    public function __construct(PostService $postService)
    {
        $this->postService = $postService;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $post = $this->postService->findBySlug($slug);
        $postsInspiration = $this->postService->getPostInspirationInDetailPost();
        return view('client.blogs.show',compact('post', 'postsInspiration'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/TourController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCustomerContactWhenBookTour;
use App\Jobs\SentEmailToAdminWhenClientApplyFormJob;
use App\Jobs\SentEmailToClientWhenApplyFormJob;
use App\Models\CustomerContact;
use App\Services\CustomerContactService;
use App\Services\SlugService;
use App\Services\TourService;
use App\Traits\CapchaCustom;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;

class TourController extends Controller
{

    use CapchaCustom;
    protected TourService $tourService;
    protected CustomerContactService $customerContactService;
    protected SlugService $slugService;

    /**
     * @param TourService $tourService
     * @param CustomerContactService $customerContactService
     * @param SlugService $slugService
     */
    public function __construct(
        TourService $tourService,
        CustomerContactService $customerContactService,
        SlugService $slugService
    ) {
        $this->tourService = $tourService;
        $this->customerContactService = $customerContactService;
        $this->slugService = $slugService;
    }


    public function index()
    {
        return  view('client.tours.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($slug)
    {
        $tour = $this->tourService->findBySlug($slug);
        $toursSimilar =  $this->tourService->getToursRandomShowInClient();
        $toursHighLight =  $this->tourService->getToursHighLight();
        return  view('client.tours.show', compact('tour','toursSimilar','toursHighLight'));
    }

    public function bookTourForm($slug)
    {

        return view('client.tours.booking');
    }

    public function bookTour(CreateCustomerContactWhenBookTour $request)
    {

        if( $this->verifyCapcha($request))
        {
            $cust = $this->customerContactService->store($request);
            $this->dispatch(new  SentEmailToClientWhenApplyFormJob($cust));
            $this->dispatch(new  SentEmailToAdminWhenClientApplyFormJob($cust));
            Flash::success('Successful registration for the tour, thank you.');
            return redirect()->back()->with(['message' => 'create succseess']);
        }else{
            Flash::error('Enter capcha');
            return redirect()->back();
        }

    }

}

resources/views/client/tours/booking.blade.php
@section('style')
    <link rel="stylesheet" href="{{asset('clients/assets/css/booking.css')}}"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
@endsection
@section('title','VietNam Tour Booking tour')
@extends('client.layouts.app')

@section('header_banner')
    <div class="header-banner header-banner-tour"></div>
@endsection
@section('main')
    <section class="bookingService container">
        <div class="top-category col-12">
            <h1 class="bookingService-title">Booking tour</h1>
            <div class="desc-category">
                Please complete your booking by giving us the details of your expecting travel. Our travel specialists
                will contact you shortly to confirm or craft your tailor made tour within 24 hour.&nbsp;
            </div>
        </div>
        <div class="row">
            @include('flash::message')
            <div class="col-sm-8 col-12">
                <div class="booking-tour-info">
                    <div class="title-tour-info"><a href="">{{$tour->name}}</a></div>
                    <div style="margin-bottom: 5px">
                        <strong>Duration</strong>: {{$tour->day}}
                        day(s) {{$tour->day > 0 ? $tour->day - 1 :$tour->day}}
                        nights
                    </div>
                    <div style="margin-bottom: 5px">
                        <strong>Physical level</strong>: Hanoi
                    </div>
                    <div style="margin-bottom: 5px">
                        <strong>TOUR_CODE</strong>: TC6882
                    </div>
                </div>
                <div class="col-12">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
                <form method="post" id="book-tour-form" action="{{route('client.tours.book_tour')}}">
                    @csrf
                    <input type="hidden" name="tour_id" value="{{$tour->id}}">
                    <div class="title-contactinfo">YOUR TRAVEL PLAN:</div>
                    <div class="row mb-3">
                        <div class="col-sm-3 col-12">Departure date: <span
                                class="text-danger">*</span>
                        </div>
                        <div class="col-sm-9 col-12 d-flex">
                            <div>
                                <input type="date" name="departure_date" id="departure_date"
                                       value="{{old('departure_date')}}"
                                       class="start_date_detail form-control"/>
                            </div>
                            <div class="form-check ms-3 w-fit-content">
                                <input class="form-check-input" name="is_flexible_date" type="checkbox" value="1"
                                    {{old('is_flexible_date') == '1' ?'checked' :''}}
                                />
                                <label class="form-check-label" for="flexCheckDefault">
                                    Flexible date
                                </label>
                            </div>

                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3 col-12">Number of person:</div>
                        <div class="col-sm-9 col-12 d-flex">
                            <select class="select_adult_detail me-2 form-select w-fit-content" name="adult">
                                @for($index = 0; $index <= 10; $index++)
                                    <option {{old('adult') == $index ? 'selected' :''}} value="{{$index}}">{{$index}}
                                        adult{{$index > 2 ?'s':''}}</option>
                                @endfor
                            </select>
                            <select class="select_adult_detail me-2 form-select w-fit-content" name="child">
                                @for($index = 0; $index <= 10; $index++)
                                    <option {{old('child') == $index ? 'selected' :''}} value="{{$index}}">{{$index}}
                                        child{{$index > 2 ?'s':''}}</option>
                                @endfor
                            </select>
                            <select class="select_adult_detail form-select w-fit-content" name="child_baby">

                                @for($index = 0; $index <= 10; $index++)
                                    <option
                                        {{old('child_baby') == $index ? 'selected' :''}} value="{{$index}}">{{$index}}
                                        child{{$index > 2 ?'babies':'baby'}}</option>
                                @endfor

                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3 col-12">Hotel Request:</div>
                        <div class="col-sm-3 col-12 d-flex">
                            <select class="form-select w-fit-content me-2" name="hotel_room_quantity">
                                @for($index = 1; $index <= 10; $index++)
                                    <option
                                        {{old('hotel_room_quantity') == $index ? 'selected' :''}} value="{{$index}}">{{$index}}
                                        room{{$index > 2 ?'s':''}}</option>
                                @endfor
                            </select>
                            <select class="form-select w-fit-content" name="hotel_class">
                                <option value="">-- Hotel Class --</option>
                                @foreach(config('data.client_hotel_class')  as $item)
                                    <option
                                        {{old('hotel_class') == $item ? 'selected' :''}}  value="{{$item}}">{{$item}}</option>

                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3 col-12">International flights:</div>
                        <div class="col-sm-3 col-12">
                            <div class="form-check ms-3">
                                <input class="form-check-input" name="international_flight" type="radio"
                                       {{old('international_flight') == '1' ?'checked' :''}}
                                       value="1"
                                >
                                <label class="form-check-label" for="flexCheckDefault">
                                    Included
                                </label>
                            </div>
                            <div class="form-check ms-3 ">
                                <input class="form-check-input" name="international_flight" type="radio" value="0"
                                    {{old('international_flight') == '0' ?'checked' :''}}
                                >
                                <label class="form-check-label" for="flexCheckDefault">
                                    Not included
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row row-contact">
                        <div class="col-sm-3 col-12">Tell us more:</div>
                        <div class=" col-sm-7 col-12">
                            <p>
                                Any specific destinations, interests, budget, activities or special occasions,... =&gt;
                                for a dream trip </p>
                            <textarea name="desc" id="request" rows="4" class="form-control">{{old('desc')}}</textarea>
                        </div>
                    </div>
                    <div class="tourbox-contactinfo" style="margin-top: 30px">
                        <div class="title-contactinfo">Contact information</div>
                        <div class="clearfix row_book">
                            <div class="row_book_2 clearfix">
                                <div class="row row-contact mb-3">
                                    <div class="col-sm-3 col-12">Your name: <span class="text-danger">*</span></div>
                                    <div class="col-sm-7 col-12">
                                        <input type="text" value="{{old('name')}}" name="name" id="name"
                                               class="contact-input form-control"
                                               style="border: 1px solid red;"/>
                                    </div>
                                </div>
                                <div class="row row-contact mb-3">
                                    <div class="col-sm-3 col-12">Your email: <span class="text-danger">*</span></div>
                                    <div class="col-sm-7 col-12">
                                        <input type="email" value="{{old('email')}}" name="email" id="email"
                                               class="contact-input form-control"
                                               style="border: 1px solid red;"/>
                                    </div>
                                </div>
                                <div class="row row-contact mb-3">
                                    <div class="col-sm-3 col-12">Your phone:</div>
                                    <div class="col-sm-7 col-12">
                                        <input value="{{old('phone_number')}}" type="text" name="phone_number"
                                               id="phone" class="contact-input form-control"/>
                                    </div>
                                </div>
                                <div class="row row-contact mb-3">
                                    <div class="col-sm-3 col-12">Country of residence: <span
                                            class="text-danger">*</span></div>
                                    <div class="col-sm-7 col-12">
                                        <select data-live-search="true" name="country" id="country"
                                                class=" form-control select_country selectpicker"
                                                style="border: 1px solid red;">
                                            <option value="" selected="selected">Select a Country</option>
                                            @foreach(config('data.countries') as $item)
                                                <option
                                                    {{old('country') == $item['name'] ? 'selected' :''}}  value="{{$item['name']}}">{{$item['name']}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-contact mb-3 mb-sm-0">
                            <div class="col-sm-3 col-12"></div>
                            <div class="col-sm-7 col-12">
                                <div style="padding-top: 30px;padding-bottom: 20px" class="text-center">
                                    * Your privacy is respected and protected
                                </div>
                                @include('client.page.capcha')
                                <div class="d-flex justify-content-center ">
                                    <button type="submit"
                                            class="btn-submit-form btn">
                                        Get my trip planned >>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-4 col-12">
                <div style="padding: 20px;background: #f5f5f5;margin-bottom: 20px">
                    <h3 style="margin-top: 0">Some Advantages of our Tours&nbsp;</h3>
                    For any request, you will be in touch with&nbsp;an experience travel expert who knows&nbsp;Myanmar
                    like no other.<br>
                    <br>
                    You are free to make changes until you&nbsp;are happy with your travel itinerary, service. All
                    details are customizable and there is no hassle or commercial action
                </div>

                <div style="padding: 20px;background: #f5f5f5;margin-bottom: 20px">
                    <h3 style="margin-top: 0">You are in a good hand</h3>
                    " We committe the highest satisfaction from the first step you send us your inquiry till the time
                    you travel and enjoy your holiday with us "<br>
                    <strong>- Mr. Zaw - Myanmar Travel Expert</strong></div>
            </div>
        </div>
    </section>
@endsection
@section('script')
    <script defer
            src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
    <script src="{{asset('clients/assets/js/capcha.js')}}"></script>

@endsection